services:
  python_services:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
      - "8765:8765"
    restart: unless-stopped

  frontend:
    build:
      context: ./gui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
